# Generated by Django 5.1.6 on 2025-02-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto en EUR/USD', max_digits=10)),
                ('modelo', models.CharField(help_text='Nombre del modelo del producto', max_length=255)),
                ('almacenamiento', models.CharField(help_text='Capacidad de almacenamiento (ej. 512GB SSD)', max_length=100)),
                ('memoria', models.CharField(help_text='Capacidad de la memoria RAM (ej. 16GB DDR4)', max_length=100)),
                ('gráfica', models.CharField(help_text='Modelo de la tarjeta gráfica (ej. NVIDIA RTX 3060)', max_length=100)),
                ('procesador', models.CharField(help_text='Modelo del procesador (ej. Intel Core i7-12700H)', max_length=100)),
                ('pantalla', models.CharField(help_text="Tamaño y resolución de la pantalla (ej. 15.6'' 1920x1080)", max_length=100)),
                ('peso', models.CharField(help_text='Peso del producto (ej. 1.5kg)', max_length=50)),
                ('color', models.CharField(help_text='Color del producto (ej. Negro, Plata)', max_length=50)),
                ('audio', models.CharField(help_text='Especificaciones de audio (ej. Dolby Atmos, Altavoces estéreo)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del producto')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización del producto')),
            ],
        ),
    ]
