# Generated by Django 5.1.6 on 2025-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='almacenamiento',
            field=models.CharField(blank=True, help_text='Capacidad de almacenamiento (ej. 512GB SSD)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='audio',
            field=models.CharField(blank=True, help_text='Especificaciones de audio (ej. Dolby Atmos, Altavoces estéreo)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Color del producto (ej. Negro, Plata)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gráfica',
            field=models.CharField(blank=True, help_text='Modelo de la tarjeta gráfica (ej. NVIDIA RTX 3060)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='memoria',
            field=models.CharField(blank=True, help_text='Capacidad de la memoria RAM (ej. 16GB DDR4)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modelo',
            field=models.CharField(blank=True, help_text='Nombre del modelo del producto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pantalla',
            field=models.CharField(blank=True, help_text="Tamaño y resolución de la pantalla (ej. 15.6'' 1920x1080)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='peso',
            field=models.CharField(blank=True, help_text='Peso del producto (ej. 1.5kg)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del producto en EUR/USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='procesador',
            field=models.CharField(blank=True, help_text='Modelo del procesador (ej. Intel Core i7-12700H)', max_length=100, null=True),
        ),
    ]
