# Generated by Django 5.1.6 on 2025-02-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_product_almacenamiento_alter_product_audio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdftranscription',
            old_name='pdf_path',
            new_name='file_path',
        ),
    ]
